# customer_sim/Dockerfile
FROM python:3.11-slim

WORKDIR /app

COPY app/ /app

# uncomment below if using dependencies
# RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "-m", "app"]

